<?php

use Microframe\Routing\Router;
use Microframe\Routing\Routes;
use PHPUnit\Framework\TestCase;

class RouterTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Routes::get('/test/router', 'WelcomeController@welcome');
        Routes::post('/test/router', 'WelcomeController@about');
        Routes::get('/test/param/{id}', 'WelcomeController@welcome');
    }

    public function testGetParams()
    {
        $_SERVER['REQUEST_URI'] = '/test/router';
        $_SERVER['REQUEST_METHOD'] = 'GET';

        list($controller, $action) = Router::getParams();

        $this->assertSame($controller, 'WelcomeController');
        $this->assertSame('welcome', $action);

        $_SERVER['REQUEST_URI'] = '/test/router';
        $_SERVER['REQUEST_METHOD'] = 'POST';

        list($controller, $action) = Router::getParams();

        $this->assertSame($controller, 'WelcomeController');
        $this->assertSame('about', $action);
    }

    public function testRouterParams()
    {
        $_SERVER['REQUEST_URI'] = '/test/param/1';
        $_SERVER['REQUEST_METHOD'] = 'GET';

        list($controller, $action, $routeParams) = Router::getParams();

        $this->assertArraySubset(['id' => 1], $routeParams);

        $this->assertSame('WelcomeController', $controller);
        $this->assertSame('welcome', $action);
    }

    public function testRouterActive()
    {
        $_SERVER['REQUEST_URI'] = '/test/param/1';

        $routePath = '/test/param/{id}';
        Routes::get($routePath, 'WelcomeController@welcome')->name('test-active-url');

        $isActive = Router::isActive('test-active-url', [
            'id' => 1,
        ]);

        $this->assertTrue($isActive);
    }
}
